// Curated dictionary of kid-friendly words (3+ letters) with emojis and simple clues for a 6-year-old!
// In Spelling Bee, letters can be reused (e.g., BEE, MOM, TREE, PUPPY, BANANA).

const KID_WORDS = {
  // Animals & Bugs
  ANT: { emoji: "🐜", clue: "A tiny bug that marches in a line" },
  APE: { emoji: "🦍", clue: "A big monkey-like animal" },
  BAT: { emoji: "🦇", clue: "Flies at night and sleeps upside down" },
  BEAR: { emoji: "🐻", clue: "A big furry animal that loves honey" },
  BEE: { emoji: "🐝", clue: "Makes honey and says buzz!" },
  BIRD: { emoji: "🐦", clue: "Has feathers and wings and flies in the sky" },
  BUG: { emoji: "🐛", clue: "A little crawling insect" },
  BUNNY: { emoji: "🐰", clue: "Has long ears and hops around" },
  CALF: { emoji: "🐮", clue: "A baby cow" },
  CAMEL: { emoji: "🐪", clue: "Lives in the desert and has humps" },
  CAT: { emoji: "🐱", clue: "A furry pet that says meow" },
  CHICK: { emoji: "🐥", clue: "A fluffy yellow baby bird" },
  CLAM: { emoji: "🐚", clue: "Lives in a shell in the ocean" },
  COW: { emoji: "🐄", clue: "Lives on a farm and says moo" },
  CRAB: { emoji: "🦀", clue: "Walks sideways on the beach with claws" },
  CROW: { emoji: "🐦‍⬛", clue: "A smart black bird that says caw" },
  CUB: { emoji: "🐻", clue: "A baby bear or baby lion" },
  DEER: { emoji: "🦌", clue: "A gentle forest animal with antlers" },
  DOG: { emoji: "🐶", clue: "A friendly pet that says woof" },
  DOVE: { emoji: "🕊️", clue: "A gentle white bird" },
  DUCK: { emoji: "🦆", clue: "Swims in the pond and says quack" },
  EAGLE: { emoji: "🦅", clue: "A big strong bird that flies high" },
  EEL: { emoji: "🐍", clue: "A long wiggly fish" },
  ELK: { emoji: "🫎", clue: "A big deer with huge antlers" },
  FISH: { emoji: "🐟", clue: "Swims in the water with fins" },
  FLEA: { emoji: "🦗", clue: "A tiny jumping bug" },
  FLY: { emoji: "🪰", clue: "A little buzzing bug with wings" },
  FOAL: { emoji: "🐴", clue: "A baby horse" },
  FOX: { emoji: "🦊", clue: "An orange forest animal with a bushy tail" },
  FROG: { emoji: "🐸", clue: "Green, hops, and says ribbit" },
  GOAT: { emoji: "🐐", clue: "Farm animal with horns that loves to climb" },
  GOOSE: { emoji: "🪿", clue: "A big bird that says honk" },
  HEN: { emoji: "🐔", clue: "A mama chicken that lays eggs" },
  HOG: { emoji: "🐷", clue: "A big pig" },
  HORSE: { emoji: "🐴", clue: "Says neigh and you can ride on its back" },
  KOALA: { emoji: "🐨", clue: "A cute gray animal that hugs trees" },
  LAMB: { emoji: "🐑", clue: "A fluffy baby sheep" },
  LION: { emoji: "🦁", clue: "A big cat that says roar!" },
  LLAMA: { emoji: "🦙", clue: "A fluffy animal with a long neck" },
  MICE: { emoji: "🐭", clue: "More than one little mouse" },
  MOLE: { emoji: "🐾", clue: "A little animal that digs tunnels underground" },
  MOTH: { emoji: "🦋", clue: "Like a butterfly that flies at night" },
  MOUSE: { emoji: "🐭", clue: "A tiny animal that loves cheese and says squeak" },
  MULE: { emoji: "🫏", clue: "Looks like a horse with long donkey ears" },
  NEWT: { emoji: "🦎", clue: "A tiny lizard-like animal that likes water" },
  OWL: { emoji: "🦉", clue: "A night bird that says hoo-hoo" },
  PANDA: { emoji: "🐼", clue: "A black and white bear that eats bamboo" },
  PAW: { emoji: "🐾", clue: "A dog's or cat's foot" },
  PET: { emoji: "🐶", clue: "An animal friend that lives with your family" },
  PIG: { emoji: "🐷", clue: "Pink farm animal that says oink" },
  PONY: { emoji: "🐴", clue: "A small horse" },
  PUG: { emoji: "🐶", clue: "A cute little dog with a wrinkly face" },
  PUP: { emoji: "🐶", clue: "A little baby dog" },
  PUPPY: { emoji: "🐶", clue: "A playful baby dog" },
  RAM: { emoji: "🐏", clue: "A sheep with big curly horns" },
  RAT: { emoji: "🐀", clue: "Looks like a big mouse with a long tail" },
  SEAL: { emoji: "🦭", clue: "Swims in the cold ocean and claps its flippers" },
  SHARK: { emoji: "🦈", clue: "A big ocean fish with lots of teeth" },
  SHEEP: { emoji: "🐑", clue: "Fluffy white farm animal that says baa" },
  SLUG: { emoji: "🐌", clue: "Like a snail without a shell" },
  SNAIL: { emoji: "🐌", clue: "Moves very slowly and carries a shell on its back" },
  SNAKE: { emoji: "🐍", clue: "Slithers on the ground and says sssss" },
  SWAN: { emoji: "🦢", clue: "A pretty white bird with a long curved neck" },
  TAIL: { emoji: "🐕", clue: "A happy dog wags this!" },
  TIGER: { emoji: "🐯", clue: "A big orange cat with black stripes" },
  TOAD: { emoji: "🐸", clue: "Looks like a bumpy frog" },
  TUNA: { emoji: "🐟", clue: "A fast ocean fish" },
  WHALE: { emoji: "🐋", clue: "The biggest animal in the ocean" },
  WING: { emoji: "🪽", clue: "Birds and bees use this to fly" },
  WOLF: { emoji: "🐺", clue: "Looks like a wild dog and howls at the moon" },
  WORM: { emoji: "🪱", clue: "Wiggles in the dirt after it rains" },
  ZEBRA: { emoji: "🦓", clue: "Looks like a horse with black and white stripes" },

  // Family, People & Body
  ARM: { emoji: "💪", clue: "Part of your body between your shoulder and hand" },
  AUNT: { emoji: "👩", clue: "Your mom's or dad's sister" },
  BABY: { emoji: "👶", clue: "A tiny new little brother or sister" },
  BACK: { emoji: "🧍", clue: "The behind part of your body" },
  BOY: { emoji: "👦", clue: "A young kid or brother" },
  CHIN: { emoji: "🙂", clue: "Part of your face right below your mouth" },
  DAD: { emoji: "👨", clue: "Another word for father or dada" },
  DADA: { emoji: "👨", clue: "A sweet word for dad" },
  EAR: { emoji: "👂", clue: "You use this to hear music and sounds" },
  EYE: { emoji: "👁️", clue: "You use this to see and blink" },
  FACE: { emoji: "😊", clue: "Has your eyes, nose, and smiling mouth" },
  FEET: { emoji: "🦶", clue: "You put your socks and shoes on these" },
  FOOT: { emoji: "🦶", clue: "At the bottom of your leg, with five toes" },
  GIRL: { emoji: "👧", clue: "A young kid or sister" },
  HAIR: { emoji: "💇‍♀️", clue: "Grows on top of your head and you brush it" },
  HAND: { emoji: "✋", clue: "Has five fingers for waving and holding things" },
  HEAD: { emoji: "🗣️", clue: "You wear a hat on top of this" },
  HEEL: { emoji: "🦶", clue: "The back part of your foot" },
  KID: { emoji: "🧒", clue: "A child just like you!" },
  KING: { emoji: "🤴", clue: "Wears a gold crown and lives in a castle" },
  KNEE: { emoji: "🦵", clue: "Bends in the middle of your leg" },
  LAP: { emoji: "🪑", clue: "Where a cat or kid sits when you are sitting down" },
  LEG: { emoji: "🦵", clue: "You use your two ___s to walk and run" },
  LIP: { emoji: "👄", clue: "Part of your mouth that smiles" },
  MAMA: { emoji: "👩", clue: "A sweet word for mom" },
  MAN: { emoji: "👨", clue: "A grown-up boy" },
  MOM: { emoji: "👩", clue: "Another word for mother or mama" },
  MOMMY: { emoji: "👩", clue: "Your loving mama" },
  NANA: { emoji: "👵", clue: "A sweet word for grandma" },
  NECK: { emoji: "🦒", clue: "Holds up your head (a giraffe has a long one!)" },
  NOSE: { emoji: "👃", clue: "Right in the middle of your face for smelling flowers" },
  PAL: { emoji: "🤝", clue: "A good friend or buddy" },
  PAPA: { emoji: "👴", clue: "A sweet word for dad or grandpa" },
  QUEEN: { emoji: "👑", clue: "Wears a sparkly crown (or the top Bee rank!)" },
  RIB: { emoji: "🦴", clue: "A bone in your chest that protects your heart" },
  SKIN: { emoji: "✋", clue: "Covers your whole body" },
  SON: { emoji: "👦", clue: "A boy child to his mom and dad" },
  TEETH: { emoji: "🦷", clue: "You brush these every morning and night" },
  TOE: { emoji: "🦶", clue: "One of the five little parts on your foot" },
  TOOTH: { emoji: "🦷", clue: "White and shiny in your smile" },
  TWIN: { emoji: "👯", clue: "Two brothers or sisters born on the same day" },

  // Food & Drink
  APPLE: { emoji: "🍎", clue: "A crunchy red or green fruit" },
  BEAN: { emoji: "🫘", clue: "A little seed we eat, like jelly ___s" },
  BEEF: { emoji: "🍔", clue: "Meat used to make hamburgers" },
  BEET: { emoji: "🫐", clue: "A dark red root vegetable" },
  BERRY: { emoji: "🍓", clue: "A sweet small fruit like a strawberry" },
  BITE: { emoji: "🍎", clue: "Chomp a piece of food with your teeth" },
  BREAD: { emoji: "🍞", clue: "Used to make toast and sandwiches" },
  BUN: { emoji: "🍔", clue: "A round roll of bread" },
  CAKE: { emoji: "🎂", clue: "Sweet treat with candles on your birthday" },
  CANDY: { emoji: "🍬", clue: "A sweet yummy treat" },
  CHEF: { emoji: "👩‍🍳", clue: "A person who cooks delicious food" },
  CHIP: { emoji: "🍪", clue: "Crunchy snack, or chocolate ___ in a cookie" },
  CONE: { emoji: "🍦", clue: "Holds a scoop of ice cream!" },
  COOK: { emoji: "🍳", clue: "Make warm food in the kitchen" },
  CORN: { emoji: "🌽", clue: "Yellow vegetable that grows on a cob" },
  CREAM: { emoji: "🍦", clue: "Cold sweet treat: ice ___!" },
  CUP: { emoji: "🥤", clue: "You drink water, milk, or juice from this" },
  DATE: { emoji: "🌴", clue: "A sweet brown fruit from a palm tree" },
  DISH: { emoji: "🍽️", clue: "A plate or bowl for food" },
  EAT: { emoji: "🍽️", clue: "Put food in your mouth and chew" },
  EGG: { emoji: "🥚", clue: "Laid by a hen and cracked for breakfast" },
  FEED: { emoji: "🥣", clue: "Give food to a pet or baby" },
  FIG: { emoji: "🍇", clue: "A soft sweet purple fruit" },
  FOOD: { emoji: "🍱", clue: "Yummy things we eat for breakfast, lunch, and dinner" },
  FORK: { emoji: "🍴", clue: "Has prongs and helps you pick up food" },
  FRUIT: { emoji: "🍉", clue: "Sweet foods like apples, bananas, and berries" },
  GRAPE: { emoji: "🍇", clue: "Small round purple or green fruit that grows in bunches" },
  GUM: { emoji: "🫧", clue: "Chewy candy you can blow bubbles with" },
  HAM: { emoji: "🥪", clue: "Pink meat often put in a sandwich" },
  HONEY: { emoji: "🍯", clue: "Sweet golden food made by busy bees!" },
  ICE: { emoji: "🧊", clue: "Frozen water that keeps your drink cold" },
  JAM: { emoji: "🍓", clue: "Sweet fruit spread that goes with peanut butter" },
  JAR: { emoji: "🫙", clue: "Glass container that holds jam or honey" },
  JUICE: { emoji: "🧃", clue: "Sweet drink made from oranges or apples" },
  KALE: { emoji: "🥬", clue: "A curly green leafy vegetable" },
  LEMON: { emoji: "🍋", clue: "A sour yellow fruit used to make lemonade" },
  LIME: { emoji: "🍋‍🟩", clue: "A sour green fruit like a lemon" },
  LUNCH: { emoji: "🥪", clue: "The meal you eat in the middle of the day" },
  MEAL: { emoji: "🍽️", clue: "Breakfast, lunch, or dinner" },
  MEAT: { emoji: "🍗", clue: "Food like chicken or beef" },
  MELON: { emoji: "🍈", clue: "A big juicy round fruit like watermelon" },
  MILK: { emoji: "🥛", clue: "White drink that goes great with cookies or cereal" },
  MINT: { emoji: "🌿", clue: "A cool fresh green leaf flavor" },
  MUG: { emoji: "☕", clue: "A big cup for warm cocoa" },
  NUT: { emoji: "🥜", clue: "A crunchy snack that squirrels love" },
  OAT: { emoji: "🥣", clue: "Grain used to make warm oatmeal" },
  PAN: { emoji: "🍳", clue: "Used on the stove to cook pancakes or eggs" },
  PEA: { emoji: "🫛", clue: "Tiny round green vegetable in a pod" },
  PEACH: { emoji: "🍑", clue: "A soft, fuzzy, sweet orange-pink fruit" },
  PEAR: { emoji: "🍐", clue: "A sweet green or yellow fruit shaped like a bell" },
  PIE: { emoji: "🥧", clue: "Baked dessert filled with apples or berries" },
  PLUM: { emoji: "🍑", clue: "A sweet purple fruit" },
  PANCAKE: { emoji: "🥞", clue: "Flat round breakfast cake with syrup" },
  PIZZA: { emoji: "🍕", clue: "Round flatbread with tomato sauce and melted cheese" },
  PLATE: { emoji: "🍽️", clue: "Flat round dish you put your food on" },
  POP: { emoji: "🍿", clue: "The sound popcorn makes!" },
  POT: { emoji: "🍲", clue: "Deep pan used for cooking soup" },
  RICE: { emoji: "🍚", clue: "Small white or brown grains we eat in a bowl" },
  ROLL: { emoji: "🥐", clue: "A small round piece of bread" },
  SALAD: { emoji: "🥗", clue: "A bowl of crunchy lettuce and vegetables" },
  SALT: { emoji: "🧂", clue: "White crystals you shake onto food" },
  SAUCE: { emoji: "🍝", clue: "Yummy liquid on pasta or apple___" },
  SEED: { emoji: "🌻", clue: "Plant this in dirt and a flower grows" },
  SIP: { emoji: "🥤", clue: "Take a little drink" },
  SNACK: { emoji: "🥨", clue: "A little bite to eat between meals" },
  SOUP: { emoji: "🥣", clue: "Warm liquid food you eat with a spoon" },
  SPOON: { emoji: "🥄", clue: "You use this to eat soup, cereal, or ice cream" },
  STEW: { emoji: "🍲", clue: "Thick warm soup with vegetables" },
  STRAW: { emoji: "🥤", clue: "Tube you sip juice or a smoothie through" },
  SUGAR: { emoji: "🧁", clue: "Makes cakes and cookies taste sweet" },
  SYRUP: { emoji: "🥞", clue: "Sweet sticky topping for pancakes" },
  TACO: { emoji: "🌮", clue: "Folded tortilla filled with yummy food" },
  TART: { emoji: "🥧", clue: "A small fruit pie" },
  TEA: { emoji: "🍵", clue: "A warm drink made from leaves in hot water" },
  TOAST: { emoji: "🍞", clue: "Warm crunchy bread from the toaster" },
  TREAT: { emoji: "🍭", clue: "Something special and yummy" },
  WATER: { emoji: "💧", clue: "Clear drink we need every day when we're thirsty" },
  YAM: { emoji: "🍠", clue: "An orange sweet potato" },

  // Nature, Weather & Space
  AIR: { emoji: "🌬️", clue: "All around us and we breathe it in" },
  BAY: { emoji: "🌊", clue: "Water next to the land where boats float" },
  BEACH: { emoji: "🏖️", clue: "Sandy place by the ocean waves" },
  BARK: { emoji: "🪵", clue: "Outside of a tree, or the sound a dog makes!" },
  BLOOM: { emoji: "🌸", clue: "When a flower opens its petals" },
  BOG: { emoji: "🐸", clue: "Wet muddy ground where frogs like to live" },
  BUD: { emoji: "🌷", clue: "A baby flower before it opens up" },
  BUSH: { emoji: "🌳", clue: "A short leafy plant smaller than a tree" },
  CAVE: { emoji: "🦇", clue: "A big dark hole inside a rocky mountain" },
  CLAY: { emoji: "🏺", clue: "Soft earth you can squish and shape into pots" },
  CLIFF: { emoji: "⛰️", clue: "A very high, steep rock wall" },
  CLOUD: { emoji: "☁️", clue: "Fluffy white shape floating in the sky" },
  COLD: { emoji: "🥶", clue: "Chilly weather when you need a warm coat" },
  COOL: { emoji: "😎", clue: "A little bit cold, or super awesome!" },
  CORAL: { emoji: "🪸", clue: "Colorful ocean reef where little fish hide" },
  CREEK: { emoji: "🏞️", clue: "A small flowing stream of water" },
  DARK: { emoji: "🌑", clue: "When the lights are off or at nighttime" },
  DAWN: { emoji: "🌅", clue: "Early morning when the sun first comes up" },
  DAY: { emoji: "☀️", clue: "When the sun is up and it's light outside" },
  DEW: { emoji: "💧", clue: "Tiny water drops on the grass in the morning" },
  DIRT: { emoji: "🪴", clue: "Brown soil in the garden where plants grow" },
  DUNE: { emoji: "🏜️", clue: "A big hill made of sand at the beach" },
  DUST: { emoji: "✨", clue: "Tiny specs of dirt or fairy ___!" },
  EARTH: { emoji: "🌍", clue: "The big blue and green planet we live on" },
  FALL: { emoji: "🍂", clue: "Season when leaves turn orange and drop down" },
  FERN: { emoji: "🌿", clue: "A feathery green forest plant" },
  FIELD: { emoji: "🌾", clue: "A big open grassy meadow" },
  FIRE: { emoji: "🔥", clue: "Hot bright flames in a campfire" },
  FLAME: { emoji: "🔥", clue: "The glowing orange part of a fire or candle" },
  FOG: { emoji: "🌫️", clue: "A cloud that comes right down to the ground" },
  FROST: { emoji: "❄️", clue: "Sparkly white ice on windows on a cold morning" },
  GALE: { emoji: "💨", clue: "A very strong blowing wind" },
  GEM: { emoji: "💎", clue: "A shiny colorful jewel rock" },
  GLOW: { emoji: "✨", clue: "Shine softly in the dark like a firefly" },
  GRASS: { emoji: "🌱", clue: "Green blades that cover the yard and park" },
  HAIL: { emoji: "🌨️", clue: "Little balls of ice that fall from storm clouds" },
  HEAT: { emoji: "☀️", clue: "Warmth from the sun or a fire" },
  HILL: { emoji: "⛰️", clue: "High grassy land fun to roll or sled down" },
  HIVE: { emoji: "🪺", clue: "The home where busy bees live together!" },
  HOT: { emoji: "🥵", clue: "Very warm, like a sunny summer day" },
  LAKE: { emoji: "🏞️", clue: "A big body of water surrounded by land" },
  LAND: { emoji: "🏝️", clue: "Solid ground that isn't water" },
  LAVA: { emoji: "🌋", clue: "Hot melted rock that comes out of a volcano" },
  LAWN: { emoji: "🏡", clue: "Mowed green grass around a house" },
  LEAF: { emoji: "🍃", clue: "Green part of a tree or plant" },
  LIGHT: { emoji: "💡", clue: "Helps us see in the dark" },
  LILY: { emoji: "🪷", clue: "A pretty flower that can float on a pond" },
  LOG: { emoji: "🪵", clue: "A thick round piece of wood from a tree" },
  MIST: { emoji: "🌫️", clue: "Tiny gentle drops of water in the air" },
  MOON: { emoji: "🌙", clue: "Shines in the sky at night" },
  MOSS: { emoji: "🪨", clue: "Soft fuzzy green plant that grows on rocks" },
  MUD: { emoji: "🥾", clue: "Wet squishy dirt after it rains" },
  NEST: { emoji: "🪹", clue: "A cozy home a bird builds in a tree" },
  NIGHT: { emoji: "🌌", clue: "When the moon and stars come out and we sleep" },
  OAK: { emoji: "🌳", clue: "A big strong tree that drops acorns" },
  OCEAN: { emoji: "🌊", clue: "Huge salty sea where whales and dolphins swim" },
  PALM: { emoji: "🌴", clue: "A beach tree where coconuts grow" },
  PARK: { emoji: "🛝", clue: "Fun place outside with grass, trees, and swings" },
  PATH: { emoji: "🛤️", clue: "A little trail to walk on in the woods" },
  PEAK: { emoji: "🏔️", clue: "The pointy very top of a mountain" },
  PETAL: { emoji: "🌸", clue: "One of the colorful soft parts of a flower" },
  PINE: { emoji: "🌲", clue: "An evergreen tree with needles and pinecones" },
  PLANT: { emoji: "🪴", clue: "Something green that grows from a seed" },
  POND: { emoji: "🦆", clue: "A small lake where ducks and frogs swim" },
  POOL: { emoji: "🏊‍♀️", clue: "Filled with water for swimming in the summer" },
  RAIN: { emoji: "🌧️", clue: "Water drops falling from the clouds" },
  REEF: { emoji: "🪸", clue: "An underwater home for colorful ocean fish" },
  RIVER: { emoji: "🏞️", clue: "Long flowing water that goes to the sea" },
  ROCK: { emoji: "🪨", clue: "A hard stone on the ground" },
  ROOT: { emoji: "🌱", clue: "Part of a plant that grows under the dirt" },
  ROSE: { emoji: "🌹", clue: "A sweet-smelling red or pink flower" },
  SAND: { emoji: "🏖️", clue: "Tiny grains at the beach for building castles" },
  SEA: { emoji: "🌊", clue: "Another word for the big salty ocean" },
  SHADE: { emoji: "⛱️", clue: "Cool spot out of the hot sun under a tree" },
  SHELL: { emoji: "🐚", clue: "Pretty hard treasure you find on the beach" },
  SKY: { emoji: "🌤️", clue: "Way up above us where clouds and birds fly" },
  SNOW: { emoji: "❄️", clue: "Soft white flakes that fall in winter" },
  SOIL: { emoji: "🌱", clue: "Garden dirt that helps flowers grow" },
  SPACE: { emoji: "🚀", clue: "Way up past the sky where stars and planets are" },
  STAR: { emoji: "⭐", clue: "Twinkles in the night sky!" },
  STEM: { emoji: "🌷", clue: "The green stalk that holds up a flower" },
  STONE: { emoji: "🪨", clue: "A smooth rock" },
  STORM: { emoji: "⛈️", clue: "Big rain with thunder and lightning" },
  SUN: { emoji: "☀️", clue: "Big bright yellow star that warms the day" },
  SUNNY: { emoji: "🌞", clue: "A bright day with lots of sunshine" },
  THORN: { emoji: "🌹", clue: "A little pokey point on a rose stem" },
  TIDE: { emoji: "🌊", clue: "When the ocean waves move in and out" },
  TREE: { emoji: "🌳", clue: "Tall plant with a trunk, branches, and leaves" },
  TWIG: { emoji: "🪵", clue: "A tiny stick from a tree branch" },
  VINE: { emoji: "🌿", clue: "A long climbing plant where grapes or pumpkins grow" },
  WARM: { emoji: "☀️", clue: "Cozy and nicely heated, not cold" },
  WAVE: { emoji: "🌊", clue: "Water rolling onto the beach, or saying hi with your hand!" },
  WEED: { emoji: "🌿", clue: "A wild plant growing in the garden" },
  WIND: { emoji: "💨", clue: "Moving air that blows kites and leaves" },
  WOOD: { emoji: "🪵", clue: "Comes from trees and is used to build things" },
  WOODS: { emoji: "🌲", clue: "A forest full of trees" },
  YARD: { emoji: "🏡", clue: "The grassy area outside a house" },

  // Home, Clothes, Toys & Things
  ART: { emoji: "🎨", clue: "Drawings, paintings, and crafts you make" },
  AXE: { emoji: "🪓", clue: "A tool for chopping wood" },
  BAG: { emoji: "🎒", clue: "Holds your things when you go places" },
  BALL: { emoji: "⚽", clue: "Round toy you throw, kick, or bounce" },
  BAND: { emoji: "🎸", clue: "A group playing music, or a hair ___" },
  BARN: { emoji: "🏚️", clue: "Big red building on a farm where cows and horses live" },
  BATH: { emoji: "🛁", clue: "Warm soapy water in the tub to get clean" },
  BEAD: { emoji: "📿", clue: "Little colorful piece you string on a necklace" },
  BED: { emoji: "🛏️", clue: "Cozy place with a pillow and blanket where you sleep" },
  BELL: { emoji: "🔔", clue: "Rings and goes ding-dong or jingle!" },
  BELT: { emoji: "👖", clue: "Goes around your waist to hold up your pants" },
  BENCH: { emoji: "🪑", clue: "A long seat in the park" },
  BIB: { emoji: "👶", clue: "A baby wears this around their neck when eating" },
  BIKE: { emoji: "🚲", clue: "Has two wheels and pedals you push with your feet" },
  BIN: { emoji: "🧺", clue: "A box or basket for storing toys" },
  BLOCK: { emoji: "🧱", clue: "Toy cube you stack up to build towers" },
  BOARD: { emoji: "🛹", clue: "Flat piece of wood, or a game ___" },
  BOAT: { emoji: "⛵", clue: "Floats and sails across the water" },
  BOOK: { emoji: "📖", clue: "Has pages and stories for you to read" },
  BOOT: { emoji: "🥾", clue: "Tall shoe for stomping in rain puddles or snow" },
  BOW: { emoji: "🎀", clue: "A pretty ribbon tied in your hair or on a present" },
  BOWL: { emoji: "🥣", clue: "Round dish for cereal or soup" },
  BOX: { emoji: "📦", clue: "Square container made of cardboard or wood" },
  BRICK: { emoji: "🧱", clue: "Hard red block used to build houses" },
  BROOM: { emoji: "🧹", clue: "Has bristles for sweeping the floor" },
  BRUSH: { emoji: "🪥", clue: "Used to smooth your hair or clean your teeth" },
  BUS: { emoji: "🚌", clue: "Big yellow vehicle that takes kids to school" },
  CAB: { emoji: "🚕", clue: "A yellow taxi car" },
  CAGE: { emoji: "🦜", clue: "An enclosure where a pet bird or hamster lives" },
  CAMP: { emoji: "⛺", clue: "Sleeping outside in a tent under the stars" },
  CAN: { emoji: "🥫", clue: "Metal container for soup or beans" },
  CANE: { emoji: "🦯", clue: "A walking stick or candy ___!" },
  CAP: { emoji: "🧢", clue: "A soft hat with a visor to shade your eyes" },
  CAPE: { emoji: "🦸‍♀️", clue: "A superhero wears this flowing on their back" },
  CAR: { emoji: "🚗", clue: "Has four wheels and drives on the road" },
  CARD: { emoji: "🃏", clue: "You play games with these or give one on a birthday" },
  CART: { emoji: "🛒", clue: "Has wheels and holds groceries at the store" },
  CASE: { emoji: "🧰", clue: "A box that holds pencils or glasses" },
  CASTLE: { emoji: "🏰", clue: "Big stone palace where kings, queens, and dragons live" },
  CHAIR: { emoji: "🪑", clue: "A seat with four legs and a back" },
  CHALK: { emoji: "🖍️", clue: "Colorful sticks for drawing on the sidewalk" },
  CHEST: { emoji: "🧰", clue: "A big box that holds pirate treasure!" },
  CLOCK: { emoji: "🕒", clue: "Has hands or numbers that tell us the time" },
  CLOTH: { emoji: "🧣", clue: "Soft fabric used to make clothes or a wash___" },
  COAT: { emoji: "🧥", clue: "Warm jacket you wear outside when it's cold" },
  COIN: { emoji: "🪙", clue: "Shiny round metal money like a penny or dime" },
  COMB: { emoji: "🪮", clue: "Has little teeth to untangle your hair" },
  COT: { emoji: "🛏️", clue: "A small folding bed" },
  COUCH: { emoji: "🛋️", clue: "Soft comfy sofa in the living room" },
  CRIB: { emoji: "👶", clue: "A little bed with sides for a baby" },
  CROWN: { emoji: "👑", clue: "Shiny gold hat worn by a Queen Bee!" },
  DESK: { emoji: "🪑", clue: "A table where you draw, write, or do schoolwork" },
  DICE: { emoji: "🎲", clue: "Little cubes with dots you roll in a board game" },
  DOCK: { emoji: "⛵", clue: "Wooden walkway where boats tie up" },
  DOLL: { emoji: "🪆", clue: "A toy shaped like a little person or baby" },
  DOOR: { emoji: "🚪", clue: "You open and close this to walk into a room" },
  DRESS: { emoji: "👗", clue: "One-piece clothing with a skirt" },
  DRUM: { emoji: "🥁", clue: "Musical instrument you tap with sticks to make a beat" },
  FAN: { emoji: "🪭", clue: "Spins or waves to blow cool air on a hot day" },
  FARM: { emoji: "🚜", clue: "Place in the country with a barn, crops, and animals" },
  FENCE: { emoji: "🏡", clue: "Goes around a yard or garden" },
  FLAG: { emoji: "🚩", clue: "Colorful cloth that waves on a pole in the wind" },
  FLUTE: { emoji: "🪈", clue: "Musical instrument you hold sideways and blow into" },
  FOAM: { emoji: "🫧", clue: "Lots of little soap bubbles in the bath" },
  FORT: { emoji: "⛺", clue: "A cozy hideout built from blankets and pillows!" },
  GAME: { emoji: "🎲", clue: "Something fun we play together!" },
  GATE: { emoji: "⛩️", clue: "A door in a fence that opens and closes" },
  GIFT: { emoji: "🎁", clue: "A wrapped present for someone special" },
  GLASS: { emoji: "🥛", clue: "What windows are made of, or a cup for water" },
  GLOVE: { emoji: "🧤", clue: "Keeps your hand and fingers warm in winter" },
  GLUE: { emoji: "🧴", clue: "Sticky stuff used to stick paper together in crafts" },
  GOLD: { emoji: "🌟", clue: "Shiny yellow treasure metal" },
  GOWN: { emoji: "👗", clue: "A fancy princess dress or night___" },
  HALL: { emoji: "🚪", clue: "Walkway inside a house that connects rooms" },
  HARP: { emoji: "🪉", clue: "Musical instrument with lots of strings you pluck" },
  HAT: { emoji: "👒", clue: "You wear this on your head" },
  HOME: { emoji: "🏠", clue: "The cozy place where you live with your family" },
  HOOD: { emoji: "🧥", clue: "The part of a jacket that goes over your head" },
  HOOK: { emoji: "🪝", clue: "Curved piece used to hang up your coat or backpack" },
  HORN: { emoji: "📯", clue: "Goes beep-beep on a car or makes music!" },
  HOSE: { emoji: "🚿", clue: "Long tube that sprays water in the garden" },
  HOUSE: { emoji: "🏠", clue: "A building where a family lives" },
  HUT: { emoji: "🛖", clue: "A small simple little house" },
  INK: { emoji: "🖊️", clue: "Colored liquid inside a pen or stamp pad" },
  JEEP: { emoji: "🚙", clue: "A bumpy-road car for adventures" },
  JET: { emoji: "✈️", clue: "A super fast airplane in the sky" },
  KEY: { emoji: "🔑", clue: "Turns in a lock to open a door" },
  KITE: { emoji: "🪁", clue: "Flies high on a string on a windy day" },
  KNOT: { emoji: "🪢", clue: "You tie shoelaces or string into this" },
  LACE: { emoji: "👟", clue: "The string you tie on your shoes" },
  LAMP: { emoji: "🛋️", clue: "Sits on a table and shines light in a room" },
  LID: { emoji: "🫙", clue: "The top cover that goes on a pot or jar" },
  LOCK: { emoji: "🔒", clue: "Keeps a door or treasure chest closed until you use a key" },
  MAP: { emoji: "🗺️", clue: "Drawing that shows roads, lands, or where treasure is hidden" },
  MASK: { emoji: "🎭", clue: "Covers your face for dress-up or Halloween" },
  MAT: { emoji: "🧘‍♀️", clue: "Small rug by the door or for tumbling on the floor" },
  MOP: { emoji: "🪣", clue: "Washes the floor with soapy water" },
  NAIL: { emoji: "🔨", clue: "Metal pin you tap into wood with a hammer, or finger___" },
  NET: { emoji: "🥅", clue: "Used to catch butterflies, fish, or a soccer ball!" },
  NOTE: { emoji: "🎵", clue: "A little message on paper, or a musical sound" },
  OAR: { emoji: "🚣", clue: "Wooden paddle used to row a boat" },
  OVEN: { emoji: "🧁", clue: "Warm kitchen box where cakes and cookies bake" },
  PAD: { emoji: "📝", clue: "Stack of paper for drawing, or a frog's lily ___" },
  PAGE: { emoji: "📄", clue: "One sheet of paper inside a book" },
  PAIL: { emoji: "🪣", clue: "A bucket you take to the beach to carry sand and water" },
  PAINT: { emoji: "🎨", clue: "Colorful liquid you put on paper with a brush" },
  PANTS: { emoji: "👖", clue: "Clothes with two legs that you wear" },
  PEN: { emoji: "🖊️", clue: "Tool with ink for writing and drawing" },
  PHONE: { emoji: "📱", clue: "Used to call and talk to grandma or friends" },
  PIANO: { emoji: "🎹", clue: "Musical instrument with black and white keys" },
  PIN: { emoji: "🧷", clue: "Little metal badge or rolling ___ for dough" },
  PIPE: { emoji: "🫧", clue: "Tube that carries water" },
  PLANE: { emoji: "✈️", clue: "Has wings and flies people high in the sky" },
  PLUG: { emoji: "🔌", clue: "Goes into the wall for a lamp, or stops water in the tub" },
  POLE: { emoji: "💈", clue: "A tall long stick like a flag___" },
  POOL: { emoji: "🏊", clue: "Big tub of water for swimming" },
  PUMP: { emoji: "🚲", clue: "Puts air into a bike tire or ball" },
  PURSE: { emoji: "👛", clue: "A small bag for carrying coins and treasures" },
  QUILT: { emoji: "🛏️", clue: "A cozy patchwork blanket for your bed" },
  RAFT: { emoji: "🛶", clue: "A flat floating boat for river adventures" },
  RAG: { emoji: "🧽", clue: "A soft cloth for wiping up spills" },
  RAKE: { emoji: "🍂", clue: "Garden tool for gathering autumn leaves into a pile" },
  RAMP: { emoji: "🛹", clue: "A sloped path that wheels can roll up and down" },
  RING: { emoji: "💍", clue: "Pretty circle worn on a finger, or the sound a bell makes" },
  ROAD: { emoji: "🛣️", clue: "Street where cars and buses drive" },
  ROBE: { emoji: "🥼", clue: "Cozy wrap you wear after a bath or over pajamas" },
  ROBOT: { emoji: "🤖", clue: "Beep-boop machine friend!" },
  ROD: { emoji: "🎣", clue: "Long pole used for fishing" },
  ROOF: { emoji: "🏠", clue: "The very top cover of a house" },
  ROOM: { emoji: "🛏️", clue: "A space inside a house, like your bed___" },
  ROPE: { emoji: "🪢", clue: "Thick strong cord for jumping or climbing" },
  RUG: { emoji: "🧶", clue: "Soft carpet on the floor" },
  SACK: { emoji: "🎒", clue: "A big cloth or paper bag" },
  SAIL: { emoji: "⛵", clue: "Big cloth on a boat that catches the wind" },
  SAW: { emoji: "🪚", clue: "Tool with teeth for cutting wood (or past of see!)" },
  SCARF: { emoji: "🧣", clue: "Soft long cloth wrapped around your neck in winter" },
  SEAT: { emoji: "💺", clue: "A place to sit down" },
  SHED: { emoji: "🛖", clue: "Small building in the yard for garden tools and bikes" },
  SHELF: { emoji: "📚", clue: "Flat board on the wall that holds books and toys" },
  SHIP: { emoji: "🚢", clue: "A very big boat that sails across the ocean" },
  SHIRT: { emoji: "👕", clue: "Top with sleeves that you wear" },
  SHOE: { emoji: "👟", clue: "You wear a pair of these on your feet outside" },
  SHOP: { emoji: "🏪", clue: "A store where you buy things" },
  SIGN: { emoji: "🪧", clue: "Board with words or pictures that shows the way" },
  SINK: { emoji: "🚰", clue: "Basin with a faucet where you wash your hands" },
  SKATE: { emoji: "⛸️", clue: "Shoe with wheels or a blade for gliding!" },
  SKIRT: { emoji: "👗", clue: "Piece of clothing that hangs down from the waist" },
  SLED: { emoji: "🛷", clue: "Slides fast down a snowy hill!" },
  SLIDE: { emoji: "🛝", clue: "Playground fun: climb the ladder and zoom down!" },
  SOAP: { emoji: "🧼", clue: "Makes bubbles and washes your hands clean" },
  SOCK: { emoji: "🧦", clue: "Soft cozy cover you put on your foot inside your shoe" },
  SOFA: { emoji: "🛋️", clue: "Another word for a comfy couch" },
  SONG: { emoji: "🎶", clue: "Music with words that you sing!" },
  SPADE: { emoji: "🪏", clue: "A little shovel for digging in sand or dirt" },
  STEP: { emoji: "🪜", clue: "One stair you walk up" },
  STICK: { emoji: "🪵", clue: "A thin piece of wood from a tree" },
  STOOL: { emoji: "🪑", clue: "A little seat without a back, or a step___" },
  STORE: { emoji: "🏪", clue: "Place where you go shopping" },
  STRING: { emoji: "🧶", clue: "Thin cord used to fly a kite or tie a balloon" },
  SUIT: { emoji: "🕴️", clue: "Matching jacket and pants, or a swim___" },
  SWING: { emoji: "🪢", clue: "Playground seat that goes back and forth in the air" },
  TABLE: { emoji: "🪑", clue: "Furniture with a flat top where we eat dinner" },
  TAPE: { emoji: "🩹", clue: "Sticky strip used to wrap presents or fix torn paper" },
  TAXI: { emoji: "🚕", clue: "A car that gives people rides around town" },
  TENT: { emoji: "⛺", clue: "Cloth house you sleep in when camping" },
  TILE: { emoji: "🟦", clue: "Square piece on a bathroom floor or in a word game" },
  TIRE: { emoji: "🛞", clue: "Round black rubber wheel on a car or bike" },
  TOOL: { emoji: "🔨", clue: "Something helpful like a hammer, wrench, or screwdriver" },
  TOP: { emoji: "🪀", clue: "A toy that spins round and round, or the highest part" },
  TOWER: { emoji: "🗼", clue: "A very tall skinny building or block stack" },
  TOWN: { emoji: "🏘️", clue: "A place with houses, shops, parks, and streets" },
  TOY: { emoji: "🧸", clue: "Something fun to play with, like a doll, truck, or ball" },
  TRACK: { emoji: "🛤️", clue: "Rails that a train rolls on" },
  TRAIN: { emoji: "🚂", clue: "Choo-choo! Rolls on tracks and pulls cars" },
  TRAY: { emoji: "🍽️", clue: "Flat board with edges for carrying food and cups" },
  TRUCK: { emoji: "🚚", clue: "Big vehicle that carries heavy things or puts out fires" },
  TUB: { emoji: "🛁", clue: "Where you take a warm bubble bath" },
  TUBE: { emoji: "🧴", clue: "Holds toothpaste or paint" },
  VAN: { emoji: "🚐", clue: "A big family car with sliding doors" },
  VASE: { emoji: "🏺", clue: "Pretty container that holds water and cut flowers" },
  VEST: { emoji: "🦺", clue: "A sleeveless jacket or life ___" },
  WAGON: { emoji: "🛻", clue: "Little red cart with four wheels and a handle to pull" },
  WALL: { emoji: "🧱", clue: "The side of a room or house" },
  WAND: { emoji: "🪄", clue: "A fairy or magician waves a magic ___!" },
  WATCH: { emoji: "⌚", clue: "A little clock you wear on your wrist" },
  WEB: { emoji: "🕸️", clue: "Silky net spun by a spider" },
  WELL: { emoji: "🪣", clue: "Deep hole in the ground with water, or feeling good!" },
  WHEEL: { emoji: "🛞", clue: "Round part that rolls on a bike, car, or wagon" },
  WIG: { emoji: "💇", clue: "Silly pretend hair you can wear for dress-up" },
  WIRE: { emoji: "🔌", clue: "Thin metal cord" },
  WOOL: { emoji: "🧶", clue: "Soft warm yarn that comes from a sheep" },
  YARN: { emoji: "🧶", clue: "Soft thick string used for knitting sweaters" },
  YOYO: { emoji: "🪀", clue: "Toy on a string that goes down and up" },
  DOT: { emoji: "🔴", clue: "A tiny round spot or circle" },
  MOO: { emoji: "🐄", clue: "The sound a cow makes!" },
  BOO: { emoji: "👻", clue: "What a silly ghost says!" },
  SUB: { emoji: "🚢", clue: "A boat that goes underwater (submarine)" },
  JUG: { emoji: "🫙", clue: "A big pitcher that holds water, milk, or juice" },
  FIN: { emoji: "🦈", clue: "Helps a fish swim in the water" },
  TIN: { emoji: "🥫", clue: "A metal box for cookies or mints" },
  KIT: { emoji: "🧰", clue: "A box of tools or craft supplies" },
  PIT: { emoji: "🍑", clue: "The hard seed in the middle of a peach or cherry" },
  LIT: { emoji: "🕯️", clue: "Shining with light, like a candle" },
  COP: { emoji: "👮", clue: "A police officer who helps keep people safe" },
  JOY: { emoji: "🥳", clue: "A big feeling of happiness!" },
  BOWS: { emoji: "🎀", clue: "Pretty ribbons!" },
  CATS: { emoji: "🐱", clue: "More than one furry kitty" },
  DOGS: { emoji: "🐶", clue: "More than one friendly puppy" },
  BUGS: { emoji: "🐞", clue: "Little crawling or flying insects" },
  BEDS: { emoji: "🛏️", clue: "Cozy places to sleep" },
  BEES: { emoji: "🐝", clue: "Lots of buzzing honey makers!" },
  TREES: { emoji: "🌳", clue: "Tall green plants in the forest" },
  STARS: { emoji: "🌟", clue: "Twinkling lights in the night sky" },
  CARS: { emoji: "🚗", clue: "Vehicles driving on the road" },
  CUPS: { emoji: "🥤", clue: "Containers you drink from" },
  HATS: { emoji: "👒", clue: "Things you wear on your head" },
  PIGS: { emoji: "🐷", clue: "Pink farm animals that say oink" },
  PUPS: { emoji: "🐶", clue: "Little baby dogs" },

  // Colors, Numbers & Describing Words
  ALL: { emoji: "🌟", clue: "Every single one" },
  BAD: { emoji: "👎", clue: "Not good" },
  BIG: { emoji: "🐘", clue: "Large and huge, like an elephant" },
  BLACK: { emoji: "🖤", clue: "Darkest color, like the night sky" },
  BLUE: { emoji: "💙", clue: "The color of a clear daytime sky" },
  BOLD: { emoji: "🦁", clue: "Brave and not afraid" },
  BRAVE: { emoji: "🦸‍♀️", clue: "Having courage like a hero" },
  BROWN: { emoji: "🤎", clue: "The color of chocolate, dirt, and tree trunks" },
  BUSY: { emoji: "🐝", clue: "Working hard like a ___ bee!" },
  CALM: { emoji: "😌", clue: "Peaceful, quiet, and relaxed" },
  CLEAN: { emoji: "✨", clue: "Washed and shiny with no dirt" },
  CUTE: { emoji: "🐣", clue: "Sweet and adorable like a puppy or kitten" },
  DEEP: { emoji: "🌊", clue: "Goes way, way down like the ocean" },
  DRY: { emoji: "☀️", clue: "Not wet at all" },
  EASY: { emoji: "👍", clue: "Simple to do, not hard" },
  FAIR: { emoji: "⚖️", clue: "Taking turns and sharing nicely" },
  FAST: { emoji: "🐆", clue: "Super quick like a cheetah or racecar" },
  FAT: { emoji: "🐱", clue: "Round and chubby" },
  FINE: { emoji: "👌", clue: "Doing well and feeling good" },
  FIVE: { emoji: "5️⃣", clue: "How many fingers are on one hand!" },
  FLAT: { emoji: "🥞", clue: "Smooth and level like a pancake" },
  FOUR: { emoji: "4️⃣", clue: "The number after three (1, 2, 3, ___!)" },
  FREE: { emoji: "🕊️", clue: "Able to fly anywhere or costs zero coins" },
  FULL: { emoji: "🥣", clue: "Filled all the way to the top" },
  FUN: { emoji: "🎉", clue: "Something that makes you laugh and enjoy playing" },
  FUNNY: { emoji: "😂", clue: "Silly and makes you giggle!" },
  GLAD: { emoji: "😊", clue: "Happy and pleased" },
  GOOD: { emoji: "⭐", clue: "Nice, well done, and great!" },
  GRAY: { emoji: "🐘", clue: "Color between black and white, like an elephant" },
  GREAT: { emoji: "🌟", clue: "Wonderful and super good!" },
  GREEN: { emoji: "💚", clue: "The color of frogs, grass, and leaves" },
  HAPPY: { emoji: "😄", clue: "Feeling joyful with a big smile!" },
  HARD: { emoji: "🪨", clue: "Solid like a rock, or tricky to do" },
  HIGH: { emoji: "🎈", clue: "Way up tall in the air" },
  HUGE: { emoji: "🦕", clue: "Extra, extra big like a dinosaur!" },
  KIND: { emoji: "💝", clue: "Helpful, gentle, and caring to others" },
  LATE: { emoji: "⏰", clue: "After the usual time" },
  LAZY: { emoji: "🦥", clue: "Wanting to rest and move slowly like a sloth" },
  LEFT: { emoji: "⬅️", clue: "The opposite side from right" },
  LOUD: { emoji: "📢", clue: "A big noisy sound!" },
  LOW: { emoji: "⬇️", clue: "Close to the ground, not high" },
  LUCKY: { emoji: "🍀", clue: "Like finding a four-leaf clover!" },
  MAD: { emoji: "😠", clue: "Feeling angry or grumpy" },
  MANY: { emoji: "✨", clue: "A whole lot of something" },
  MEAN: { emoji: "😠", clue: "Not nice (or what a word is about)" },
  NEAT: { emoji: "✨", clue: "Tidy, clean, and put away nicely" },
  NEW: { emoji: "🆕", clue: "Brand shiny and not old" },
  GENTLE: { emoji: "🪶", clue: "Soft and careful, like petting a bunny" },
  NICE: { emoji: "😊", clue: "Kind and friendly" },
  NINE: { emoji: "9️⃣", clue: "The number right before ten" },
  ODD: { emoji: "🤪", clue: "A little bit unusual or silly" },
  OLD: { emoji: "🐢", clue: "Has been around for a long time" },
  ONE: { emoji: "1️⃣", clue: "The very first counting number" },
  OPEN: { emoji: "🔓", clue: "Not closed or shut" },
  PALE: { emoji: "🌸", clue: "A very light, soft color" },
  PINK: { emoji: "🩷", clue: "The color of flamingos and cotton candy" },
  POOR: { emoji: "🥺", clue: "Needing help or a hug" },
  PROUD: { emoji: "🏅", clue: "Feeling happy about something you worked hard on!" },
  PURE: { emoji: "💧", clue: "Clean and clear" },
  QUICK: { emoji: "⚡", clue: "Fast and speedy" },
  QUIET: { emoji: "🤫", clue: "Shhh! Making almost no sound" },
  RARE: { emoji: "🦄", clue: "Special and not seen very often" },
  REAL: { emoji: "🌟", clue: "True and not pretend" },
  RED: { emoji: "❤️", clue: "The color of strawberries, firetrucks, and hearts" },
  RICH: { emoji: "👑", clue: "Having lots of treasure or yummy flavor" },
  RIPE: { emoji: "🍌", clue: "When a fruit is ready and sweet to eat" },
  ROUND: { emoji: "⚪", clue: "Shaped like a circle or a ball" },
  RUDE: { emoji: "🙅", clue: "Not polite" },
  SAFE: { emoji: "🛡️", clue: "Protected and out of danger" },
  SAD: { emoji: "😢", clue: "Feeling down or wanting a hug" },
  SAME: { emoji: "👯", clue: "Matching and just alike" },
  SEVEN: { emoji: "7️⃣", clue: "The number after six" },
  SHARP: { emoji: "✏️", clue: "Has a pointy tip like a newly sharpened pencil" },
  SHINY: { emoji: "✨", clue: "Sparkly and bright like a new coin" },
  SHORT: { emoji: "📏", clue: "Not tall or not long" },
  SHY: { emoji: "🙈", clue: "Feeling quiet around new people" },
  SICK: { emoji: "🤒", clue: "Not feeling well and needing rest" },
  SILLY: { emoji: "🤪", clue: "Goofy and funny!" },
  SIX: { emoji: "6️⃣", clue: "One more than five (how many legs a bee has!)" },
  SLIM: { emoji: "🌱", clue: "Thin and slender" },
  SLOW: { emoji: "🐢", clue: "Moving without hurry, like a turtle or snail" },
  SMALL: { emoji: "🐭", clue: "Little and tiny" },
  SMART: { emoji: "🧠", clue: "Clever and good at learning!" },
  SOFT: { emoji: "🧸", clue: "Cozy and gentle to touch, like a teddy bear" },
  SORE: { emoji: "🩹", clue: "Hurting a little bit" },
  SOUR: { emoji: "🍋", clue: "Puckery taste like a lemon!" },
  STILL: { emoji: "🧘", clue: "Not moving at all" },
  SURE: { emoji: "✅", clue: "Certain about something" },
  SWEET: { emoji: "🍯", clue: "Tastes like honey or sugar, or very kind!" },
  TALL: { emoji: "🦒", clue: "Reaching high up like a giraffe or tree" },
  TAME: { emoji: "🐶", clue: "Gentle and friendly with people, not wild" },
  TAN: { emoji: "🐪", clue: "Light brown color like beach sand" },
  TEN: { emoji: "🔟", clue: "How many fingers you have on both hands!" },
  THICK: { emoji: "📕", clue: "Wide and not thin" },
  THIN: { emoji: "📄", clue: "Slender and flat like a sheet of paper" },
  THREE: { emoji: "3️⃣", clue: "The number after two (1, 2, ___!)" },
  TIDY: { emoji: "🧹", clue: "Neat and cleaned up" },
  TINY: { emoji: "🐜", clue: "Very, very small like an ant" },
  TIRED: { emoji: "🥱", clue: "Sleepy and ready for a nap or bed" },
  TRUE: { emoji: "✅", clue: "Real and honest" },
  TWO: { emoji: "2️⃣", clue: "The number after one (a pair!)" },
  WET: { emoji: "💦", clue: "Covered in water" },
  WHITE: { emoji: "🤍", clue: "The color of snow, milk, and fluffy clouds" },
  WIDE: { emoji: "👐", clue: "Stretched far from side to side" },
  WILD: { emoji: "🦁", clue: "Living free in nature" },
  WISE: { emoji: "🦉", clue: "Smart and thoughtful like an old owl" },
  YOUNG: { emoji: "🐣", clue: "Not old; little and growing" },
  ZERO: { emoji: "0️⃣", clue: "The number that means none at all" },

  // Actions & Everyday Words
  ACT: { emoji: "🎭", clue: "Pretend to be a character in a play" },
  ADD: { emoji: "➕", clue: "Put numbers or things together" },
  ASK: { emoji: "🙋‍♀️", clue: "Use a question to find out something" },
  BAKE: { emoji: "🧁", clue: "Make cookies, bread, or cake in the oven" },
  BEND: { emoji: "🤸‍♀️", clue: "Curve your knees or touch your toes" },
  BLOW: { emoji: "🫧", clue: "Puff air out of your mouth for bubbles or candles" },
  BOIL: { emoji: "🫧", clue: "When hot water gets bubbly" },
  BOOM: { emoji: "💥", clue: "A big loud thunder or drum sound!" },
  CALL: { emoji: "📞", clue: "Shout out to someone or ring them on the phone" },
  CARE: { emoji: "🤗", clue: "Love and help someone" },
  CATCH: { emoji: "🧤", clue: "Grab a ball that is thrown to you" },
  CHEER: { emoji: "🥳", clue: "Shout hooray and clap!" },
  CHEW: { emoji: "🦷", clue: "Crunch food with your teeth before swallowing" },
  CHOP: { emoji: "🥕", clue: "Cut vegetables into little pieces" },
  CLAP: { emoji: "👏", clue: "Put your hands together to make a happy sound" },
  CLIMB: { emoji: "🧗‍♀️", clue: "Go up a tree or playground ladder" },
  CLOSE: { emoji: "🚪", clue: "Shut a door or book" },
  COME: { emoji: "👋", clue: "Move closer to here" },
  COUNT: { emoji: "🔢", clue: "Say numbers in order: 1, 2, 3, 4, 5!" },
  CRAWL: { emoji: "👶", clue: "Move on hands and knees like a baby or bug" },
  CRY: { emoji: "😢", clue: "When tears fall from your eyes" },
  CUDDLE: { emoji: "🤗", clue: "Snuggle close and hug warmly" },
  CUT: { emoji: "✂️", clue: "Snip paper with scissors" },
  DANCE: { emoji: "💃", clue: "Move and twirl your body to music!" },
  DIG: { emoji: "🪏", clue: "Scoop up dirt or sand to make a hole" },
  DIP: { emoji: "🍓", clue: "Dunk a cookie in milk or a toe in water" },
  DIVE: { emoji: "🤿", clue: "Jump headfirst into the swimming pool" },
  DRAW: { emoji: "🖍️", clue: "Make a picture with crayons, markers, or pencils" },
  DREAM: { emoji: "💭", clue: "Stories and pictures in your mind while you sleep" },
  DRINK: { emoji: "🥤", clue: "Swallow water, milk, or juice" },
  DRIP: { emoji: "💧", clue: "When water falls drop by drop" },
  DRIVE: { emoji: "🚗", clue: "Steer a car or bus down the road" },
  DROP: { emoji: "💧", clue: "Let something fall down, or a little bead of water" },
  EARN: { emoji: "⭐", clue: "Get stars or rewards by doing a great job" },
  FEEL: { emoji: "🤚", clue: "Touch something soft or have an emotion" },
  FILL: { emoji: "🪣", clue: "Pour water or sand into a bucket until it's full" },
  FIND: { emoji: "🔍", clue: "Spot something you were looking for!" },
  FIT: { emoji: "🧩", clue: "Be just the right size, like a puzzle piece" },
  FIX: { emoji: "🛠️", clue: "Repair something that broke" },
  FLIP: { emoji: "🥞", clue: "Turn a pancake or do a tumble in the air" },
  FLOAT: { emoji: "🛟", clue: "Stay on top of the water without sinking" },
  FLOW: { emoji: "🌊", clue: "Move smoothly like water in a river" },
  FOLD: { emoji: "📄", clue: "Bend paper or clothes neatly in half" },
  GET: { emoji: "🤲", clue: "Receive or go pick something up" },
  GIVE: { emoji: "🎁", clue: "Share or hand something to someone" },
  GLIDE: { emoji: "🦢", clue: "Move smoothly like a skater or a bird in the air" },
  GO: { emoji: "🟢", clue: "Green light means ___!" },
  GRAB: { emoji: "✊", clue: "Take hold of something quickly with your hand" },
  GRIN: { emoji: "😁", clue: "A big toothy smile!" },
  GROW: { emoji: "🌱", clue: "Get bigger and taller every year" },
  GUESS: { emoji: "🤔", clue: "Try to think of the answer" },
  HANG: { emoji: "🧥", clue: "Put your coat on a hook" },
  HAVE: { emoji: "🤲", clue: "Hold or own something" },
  HEAL: { emoji: "🩹", clue: "When a scrape or boo-boo gets all better" },
  HEAR: { emoji: "👂", clue: "Listen to sounds with your ears" },
  HELP: { emoji: "🤝", clue: "Do something kind to make things easier for someone" },
  HIDE: { emoji: "🙈", clue: "Go where nobody can see you in ___-and-seek!" },
  HIT: { emoji: "⚾", clue: "Tap a baseball with a bat" },
  HOLD: { emoji: "🤲", clue: "Keep something in your hands or arms" },
  HOP: { emoji: "🐰", clue: "Jump up and down on one foot or like a bunny!" },
  HOPE: { emoji: "🤞", clue: "Wish for something good to happen" },
  HUG: { emoji: "🤗", clue: "Wrap your arms around someone you love!" },
  HUM: { emoji: "🎶", clue: "Sing a tune with your lips closed: mmm-mmm!" },
  HUNT: { emoji: "🔎", clue: "Search around for Easter eggs or treasure" },
  JOG: { emoji: "🏃‍♀️", clue: "Run at a steady, easy pace" },
  JOIN: { emoji: "🤝", clue: "Come play together or connect two pieces" },
  JOKE: { emoji: "🤡", clue: "Something funny you say to make friends laugh" },
  JUMP: { emoji: "🦘", clue: "Push off the ground with your feet into the air!" },
  KEEP: { emoji: "🤲", clue: "Hold on to something" },
  KICK: { emoji: "⚽", clue: "Hit a soccer ball with your foot" },
  KISS: { emoji: "😘", clue: "A sweet smooch on the cheek from mom or dad" },
  KNIT: { emoji: "🧶", clue: "Make a warm scarf or blanket out of yarn" },
  KNOW: { emoji: "💡", clue: "Understand or remember something" },
  LAUGH: { emoji: "😆", clue: "Giggle and go ha-ha-ha!" },
  LEAD: { emoji: "🦆", clue: "Go in front and show the way" },
  LEAN: { emoji: "🧍", clue: "Rest against a wall or bend to one side" },
  LEAP: { emoji: "🐸", clue: "Make a big long jump like a frog!" },
  LEARN: { emoji: "📚", clue: "Find out how to do something new" },
  LICK: { emoji: "🍦", clue: "Use your tongue to eat an ice cream cone" },
  LIFT: { emoji: "🏋️‍♀️", clue: "Pick something up high" },
  LIKE: { emoji: "👍", clue: "Enjoy something!" },
  LIVE: { emoji: "🏡", clue: "Make your home somewhere" },
  LOOK: { emoji: "👀", clue: "Use your eyes to see" },
  LOSE: { emoji: "🔍", clue: "Not be able to find something" },
  LOVE: { emoji: "❤️", clue: "Care about someone with all your heart!" },
  MAKE: { emoji: "🎨", clue: "Build, draw, or create something" },
  MARCH: { emoji: "🥁", clue: "Walk with big steady steps like in a parade" },
  MEET: { emoji: "👋", clue: "Say hello to a friend" },
  MELT: { emoji: "🫠", clue: "When ice or a snowman turns into water in the sun" },
  MISS: { emoji: "💭", clue: "Wish someone was with you" },
  MIX: { emoji: "🥣", clue: "Stir ingredients together in a bowl" },
  MOVE: { emoji: "🕺", clue: "Go from one spot to another, not stay still" },
  NAME: { emoji: "🏷️", clue: "The special word people call you (like Haze!)" },
  NAP: { emoji: "😴", clue: "A short little sleep during the day" },
  NEED: { emoji: "🤲", clue: "Have to have something important" },
  NOD: { emoji: "🙂", clue: "Move your head up and down to say yes" },
  PACK: { emoji: "🧳", clue: "Put clothes and toys into a bag for a trip" },
  PAT: { emoji: "🐶", clue: "Tap gently with your hand" },
  PEEK: { emoji: "🫣", clue: "Take a quick little look!" },
  PEEL: { emoji: "🍌", clue: "Take the skin off a banana or orange" },
  PET: { emoji: "🐱", clue: "Stroke a dog or cat gently" },
  PICK: { emoji: "🍓", clue: "Choose something, or gather berries and flowers" },
  PLAN: { emoji: "🗺️", clue: "Decide what fun things you're going to do" },
  PLAY: { emoji: "🤸‍♀️", clue: "Have fun with toys, games, and friends!" },
  POKE: { emoji: "👉", clue: "Touch lightly with one finger" },
  POUR: { emoji: "🫗", clue: "Tip a pitcher so juice or water flows into a cup" },
  PULL: { emoji: "🛻", clue: "Tug something toward you, like a wagon" },
  PUSH: { emoji: "🛒", clue: "Press against something to move it forward" },
  PUT: { emoji: "📥", clue: "Set something down in a spot" },
  RACE: { emoji: "🏁", clue: "Run fast to see who reaches the finish line first!" },
  READ: { emoji: "📚", clue: "Look at words in a book and understand the story" },
  REST: { emoji: "🛋️", clue: "Relax and take a break when you're tired" },
  RIDE: { emoji: "🚲", clue: "Go on a bike, horse, bus, or train" },
  ROAR: { emoji: "🦁", clue: "Make a big loud lion or dinosaur sound!" },
  ROLL: { emoji: "🎳", clue: "Turn over and over like a ball on the floor" },
  ROW: { emoji: "🚣‍♀️", clue: "Use oars to move a boat, or a neat line of things" },
  RUB: { emoji: "👐", clue: "Move your hands back and forth on something" },
  RUN: { emoji: "🏃‍♀️", clue: "Move super fast on your feet!" },
  RUSH: { emoji: "💨", clue: "Hurry quickly" },
  SAVE: { emoji: "🐷", clue: "Keep coins in a piggy bank or rescue someone" },
  SAY: { emoji: "💬", clue: "Speak words out loud" },
  SEE: { emoji: "👀", clue: "Spot something with your eyes" },
  SEEK: { emoji: "🔍", clue: "Look for someone in hide-and-___!" },
  SELL: { emoji: "🍋", clue: "Trade lemonade or goods for coins" },
  SEND: { emoji: "📬", clue: "Mail a letter or card to someone" },
  SET: { emoji: "🍽️", clue: "Put plates on the table" },
  SEW: { emoji: "🪡", clue: "Stitch cloth together with a needle and thread" },
  SHAKE: { emoji: "🪇", clue: "Wiggle something fast up and down or side to side" },
  SHARE: { emoji: "🤲", clue: "Let a friend play with your toys or have some of your snack" },
  SHINE: { emoji: "🌟", clue: "Glow brightly like the sun or stars" },
  SHOW: { emoji: "🖼️", clue: "Let someone see what you made" },
  SHUT: { emoji: "🚪", clue: "Close a door or box" },
  SING: { emoji: "🎤", clue: "Make music with your voice!" },
  SIT: { emoji: "🪑", clue: "Rest on a chair or on the floor" },
  SKIP: { emoji: "👧", clue: "Step-hop, step-hop happily down the path!" },
  SLEEP: { emoji: "😴", clue: "Close your eyes in bed at night and rest" },
  SLIP: { emoji: "🍌", clue: "Slide by accident on ice or a wet floor" },
  SMILE: { emoji: "😊", clue: "Curve your mouth up when you are happy!" },
  SMELL: { emoji: "🌸", clue: "Use your nose to sniff a flower or cookies baking" },
  SNAP: { emoji: "🫰", clue: "Click your fingers or fasten a button" },
  SOAR: { emoji: "🦅", clue: "Fly high in the sky like a bird" },
  SPELL: { emoji: "🔤", clue: "Put letters together to make a word—just like now!" },
  SPIN: { emoji: "🌀", clue: "Twirl around and around in a circle" },
  SPILL: { emoji: "🥛", clue: "When water or milk tips over by accident" },
  SPLASH: { emoji: "💦", clue: "Jump in a puddle and make water fly!" },
  SPOT: { emoji: "🐞", clue: "A round dot on a ladybug, or to see something" },
  STACK: { emoji: "🧱", clue: "Pile blocks or books on top of each other" },
  STAND: { emoji: "🧍‍♀️", clue: "Be up on your two feet" },
  START: { emoji: "🏁", clue: "Begin!" },
  STAY: { emoji: "🛑", clue: "Remain in the same place" },
  STIR: { emoji: "🥄", clue: "Move a spoon around in a bowl or cup" },
  STOP: { emoji: "🛑", clue: "Red light means ___!" },
  SWIM: { emoji: "🏊‍♀️", clue: "Move through the water like a fish" },
  TAKE: { emoji: "🤲", clue: "Reach out and hold something" },
  TALK: { emoji: "🗣️", clue: "Use words to chat with a friend" },
  TAP: { emoji: "👆", clue: "Touch lightly, like pressing a letter on the screen!" },
  TASTE: { emoji: "😋", clue: "Try food with your tongue to see how yummy it is" },
  TEACH: { emoji: "👩‍🏫", clue: "Help someone learn something new" },
  TEAR: { emoji: "💧", clue: "A drop from your eye when crying, or rip paper" },
  TELL: { emoji: "🗣️", clue: "Share a story or answer with someone" },
  THANK: { emoji: "🙏", clue: "Say '___ you!' when someone is kind" },
  THINK: { emoji: "🤔", clue: "Use your brain to have an idea" },
  THROW: { emoji: "⚾", clue: "Toss a ball through the air" },
  TICKLE: { emoji: "🪶", clue: "Touch lightly to make someone giggle: coochie-coo!" },
  TIE: { emoji: "👟", clue: "Make a bow or knot in your shoelaces" },
  TIP: { emoji: "🫗", clue: "Lean to one side, or the pointy end" },
  TOSS: { emoji: "🤾‍♀️", clue: "Throw lightly into the air" },
  TOUCH: { emoji: "👉", clue: "Feel something with your fingers" },
  TRIP: { emoji: "🧳", clue: "A fun journey, or stumble over your feet" },
  TRY: { emoji: "💪", clue: "Give something your best effort!" },
  TUG: { emoji: "🪢", clue: "Pull hard on a rope" },
  TURN: { emoji: "🔄", clue: "Spin around or take your ___ in a game" },
  USE: { emoji: "🖍️", clue: "Do something with a tool or crayon" },
  WAIT: { emoji: "⏳", clue: "Stay patient until it is time" },
  WAKE: { emoji: "⏰", clue: "Open your eyes in the morning after sleeping" },
  WALK: { emoji: "🚶‍♀️", clue: "Move forward step by step on your feet" },
  WANT: { emoji: "🤲", clue: "Wish to have something" },
  WASH: { emoji: "🧼", clue: "Clean with water and soap" },
  WEAR: { emoji: "👕", clue: "Have clothes, shoes, or a hat on your body" },
  WIN: { emoji: "🏆", clue: "Come in first or finish the game!" },
  WIPE: { emoji: "🧻", clue: "Clean or dry something with a cloth or tissue" },
  WISH: { emoji: "🌠", clue: "What you make when you blow out birthday candles!" },
  WORK: { emoji: "🐝", clue: "Do a job like a busy bee" },
  WRAP: { emoji: "🎁", clue: "Cover a birthday present with pretty paper" },
  YAWN: { emoji: "🥱", clue: "Open your mouth wide when you feel sleepy" },
  YELL: { emoji: "📣", clue: "Shout in a very loud voice" },
  ZIP: { emoji: "🧥", clue: "Pull the zipper up on your coat!" },
  ZOO: { emoji: "🦁", clue: "Park where you can visit lions, elephants, and monkeys" },
  ZOOM: { emoji: "🏎️", clue: "Go super fast!" }
};

// Additional simple valid words (3+ letters) so that if a child or parent types a real everyday word
// that doesn't have a specific emoji card above, it still counts and gives stars!
const EXTRA_VALID_WORDS = new Set([
  "ACE", "ACT", "AGE", "AID", "AIM", "ALE", "AND", "ANY", "ARC", "ARE", "ARK", "ART", "ASH", "ATE", "AWE",
  "baa", "BAN", "BAR", "BAY", "BET", "BID", "BIT", "BOB", "BOO", "BOW", "BUM", "BUT", "BUY",
  "CAM", "CAR", "COB", "COD", "COG", "COO", "COP", "COX", "COY", "CUE",
  "DAB", "DAM", "DEN", "DID", "DIE", "DIM", "DIN", "DOE", "DON", "DOT", "DUB", "CLAN", "CLAP", "CLAW",
  "DUE", "DUG", "DYE", "ERA", "EVE", "EWE", "FAD", "FAR", "FED", "FEE", "FEW", "FIN", "FIR", "FOE", "FOR",
  "FUR", "GAB", "GAG", "GAP", "GAS", "GEL", "GIG", "GIN", "GOB", "GOD", "GOT", "GUN", "GUT", "GUY", "GYM",
  "HAD", "HAG", "HAS", "HAY", "HEM", "HER", "HEW", "HEX", "HEY", "HID", "HIM", "HIP", "HIS", "HOE", "HOP",
  "HOW", "HUB", "HUE", "ILL", "IMP", "INN", "ION", "IRE", "IRK", "IVY", "JAB", "JAG", "JAW", "JAY", "JIG",
  "JOB", "JOT", "JOY", "JUG", "JUT", "KEG", "KEN", "KIN", "KIT", "LAB", "LAD", "LAG", "LAW", "LAY", "LED",
  "LET", "LIE", "LIT", "LOB", "LOT", "LOW", "LUG", "MAR", "MAW", "MAY", "MEN", "MET", "MID", "MOB", "MOM",
  "MOO", "MOW", "NAB", "NAG", "NAY", "NIB", "NIL", "NIP", "NIT", "NOR", "NOT", "NOW", "NUN", "OAF", "ODD",
  "ODE", "OFF", "OFT", "OIL", "OPT", "ORB", "ORE", "OUR", "OUT", "OWE", "OWN", "PAL", "PAM", "PAR", "PAY",
  "PEG", "PEP", "PER", "PEW", "PIT", "PLY", "POD", "POI", "POW", "PRY", "PUB", "PUN", "PUT", "RAD", "RAM",
  "RAN", "RAP", "RAW", "RAY", "RIB", "RID", "RIG", "RIM", "RIP", "ROB", "ROE", "ROT", "RUE", "RUM", "RUT",
  "RYE", "SAG", "SAP", "SAT", "SET", "SHE", "SHY", "SIN", "SIR", "SIS", "SKI", "SLY", "SOB", "SOD", "SOP",
  "SOT", "SOW", "SOY", "SPA", "SPY", "SUB", "SUE", "SUM", "TAB", "ADDS", "AGED", "AGES", "AIDE", "AILS",
  "AIMS", "AIRS", "AIRY", "AKIN", "ALLY", "ALOE", "ALSO", "ALTO", "AMID", "ANEW", "ANTE", "ANTI", "ANTS",
  "APES", "APEX", "ARCH", "AREA", "ARMS", "ARMY", "ARTS", "ASHY", "ASKS", "ATOM", "ATOP", "AUTO", "AVID",
  "AWAY", "AWED", "AWRY", "AXES", "AXIS", "AXLE", "BABE", "BAGS", "BAIL", "BAIT", "BAKE", "BALD", "BALE",
  "BALK", "BALL", "BALM", "BAND", "BANE", "BANG", "BANK", "BARE", "BARK", "BARN", "BARS", "BASE", "BASH",
  "BASK", "BASS", "BATH", "BATS", "BAWL", "BAYS", "BEAD", "BEAK", "BEAM", "BEAN", "BEAR", "BEAT", "BEAU",
  "BECK", "BEDS", "BEEF", "BEEN", "BEEP", "BEES", "BEET", "BEGS", "BELL", "BELT", "BEND", "BENT", "BEST",
  "BETS", "BIAS", "BIBS", "BIDE", "BIDS", "BIKE", "BILE", "BILL", "BIND", "BINS", "BIRD", "BITE", "BITS",
  "BLAB", "BLAH", "BLED", "BLEW", "BLIP", "BLOB", "BLOC", "BLOT", "BLOW", "BLUE", "BLUR", "BOAR", "BOAT",
  "BODE", "BODY", "BOGS", "BOIL", "BOLD", "BOLE", "BOLL", "BOLT", "BOMB", "BOND", "BONE", "BONK", "BONY",
  "BOOK", "BOOM", "BOON", "BOOR", "BOOT", "BORE", "BORN", "BOSS", "BOTH", "BOUT", "BOWL", "BOWS", "BOYS",
  "BRAD", "BRAG", "BRAN", "BRAT", "BRAY", "BRED", "BREW", "BRIM", "BROW", "BUCK", "BUDS", "BUFF", "BUGS",
  "BULB", "BULK", "BULL", "BUMP", "BUMS", "BUNK", "BUNS", "BUNT", "BUOY", "BURN", "BURP", "BURR", "BURY",
  "BUSH", "BUSK", "BUST", "BUSY", "BUTS", "BUTT", "BUYS", "BUZZ", "BYTE", "CABS", "CAFE", "CAGE", "CAKE",
  "CALF", "CALL", "CALM", "CAME", "CAMP", "CAMS", "CANE", "CANS", "CAPE", "CAPS", "CARD", "CARE", "CARP",
  "CARS", "CART", "CASE", "CASH", "CASK", "CAST", "CATS", "CAVE", "CELL", "CENT", "CHAR", "CHAT", "CHEF",
  "CHEW", "CHIN", "CHIP", "CHOP", "CHOW", "CHUG", "CHUM", "CITE", "CITY", "CLAD", "CLAM", "CLAN", "CLAP",
  "CLAW", "CLAY", "CLEF", "CLIP", "CLOD", "CLOG", "CLOP", "CLOT", "CLUB", "CLUE", "COAL", "COAT", "COAX",
  "COBS", "CODE", "COIL", "COIN", "COLA", "COLD", "COLE", "COLT", "COMB", "COME", "CONE", "COOK", "COOL",
  "COOP", "COOT", "COPE", "COPS", "COPY", "CORD", "CORE", "CORK", "CORN", "COST", "COSY", "COTS", "COVE",
  "COWL", "COWS", "COZY", "CRAB", "CRAG", "CRAM", "CREW", "CRIB", "CROP", "CROW", "CUBE", "CUBS", "CUED",
  "CUES", "CUFF", "CULL", "CUPS", "CURB", "CURD", "CURE", "CURL", "CUTE", "CUTS", "DABS", "DADS", "DAFT",
  "DALE", "DAME", "DAMP", "DAMS", "DARE", "DARK", "DARN", "DART", "DASH", "DATA", "DATE", "DAWN", "DAYS",
  "DAZE", "DEAD", "DEAF", "DEAL", "DEAN", "DEAR", "DEBT", "DECK", "DEED", "DEEM", "DEEP", "DEER", "DEFT",
  "DEFY", "DELI", "DELL", "DEMO", "DENS", "DENT", "DENY", "DESK", "DEWY", "DIAL", "DICE", "DIED", "DIES",
  "DIET", "DIGS", "DIKE", "DILL", "DIME", "DIMS", "DINE", "DING", "DINT", "DIPS", "DIRE", "DIRT", "DISC",
  "DISH", "DISK", "DIVE", "DOCK", "DOER", "DOES", "DOGS", "DOLL", "DOME", "DONE", "DOOM", "DOOR", "DOPE",
  "DORK", "DORM", "DOSE", "DOTE", "DOTS", "DOUR", "DOVE", "DOWN", "DOZE", "DRAB", "DRAG", "DRAM", "DRAW",
  "DRAY", "DREW", "DRIP", "DROP", "DRUB", "DRUG", "DRUM", "DUAL", "DUBS", "DUCK", "DUCT", "DUDE", "DUDS",
  "DUEL", "DUES", "DUET", "DUKE", "DULL", "DULY", "DUMB", "DUMP", "DUNE", "DUNG", "DUNK", "DUPE", "DUSK",
  "DUST", "DUTY", "DYED", "DYES", "EACH", "EARL", "EARN", "EARS", "EASE", "EAST", "EASY", "EATS", "EBBS",
  "ECHO", "EDGE", "EDGY", "EDIT", "EELS", "EGGS", "ELKS", "ELMS", "ELSE", "EMIT", "ENDS", "ENVY", "EPIC",
  "EVEN", "EVER", "EVIL", "EXAM", "EXIT", "EYED", "EYES", "FACE", "FACT", "FADE", "FADS", "FAIL", "FAIR",
  "FAKE", "FALL", "FAME", "FANG", "FANS", "FARE", "FARM", "FAST", "FATE", "FAWN", "FEAR", "FEAT", "FEED",
  "FEEL", "FEES", "FEET", "FELL", "FELT", "FEND", "FERN", "FEST", "FEUD", "FIGS", "FILE", "FILL", "FILM",
  "FIND", "FINE", "FINK", "FINS", "FIRE", "FIRM", "DIRS", "FISH", "FIST", "FITS", "FIVE", "FIZZ", "FLAG",
  "FLAK", "FLAN", "FLAP", "FLAT", "FLAW", "FLAX", "FLAY", "FLEA", "FLED", "FLEE", "FLEW", "FLEX", "FLIP",
  "FLIT", "FLOE", "FLOP", "FLOW", "FLUB", "FLUE", "FLUX", "FOAL", "FOAM", "FOES", "FOGS", "FOIL", "FOLD",
  "FOLK", "FOND", "FONT", "FOOD", "FOOL", "FOOT", "FORD", "FORE", "FORK", "FORM", "FORT", "FOUL", "FOUR",
  "FOWL", "FOXY", "FRAY", "FREE", "FRET", "FROG", "FROM", "FUEL", "FULL", "FUME", "FUND", "FUNK", "FURS",
  "FURY", "FUSE", "FUSS", "FUZZ", "GABS", "GAGS", "GAIN", "GAIT", "GALA", "GALE", "GALL", "GAME", "GANG",
  "GAPE", "GAPS", "GARB", "GASH", "GASP", "GATE", "GAVE", "GAWK", "GAZE", "GEAR", "GEEK", "GELS", "GEMS",
  "GENE", "GENT", "GERM", "GETS", "GIFT", "GIGS", "GILD", "GILL", "GILT", "GIRL", "GIST", "GIVE", "GLAD",
  "GLEE", "GLEN", "GLIB", "GLOB", "GLOM", "GLOP", "GLOW", "GLUE", "GLUM", "GLUT", "GNAT", "GNAW", "GOAD",
  "GOAL", "GOAT", "GOBS", "GODS", "GOER", "GOES", "GOLD", "GOLF", "GONE", "GONG", "GOOD", "GOOF", "GOON",
  "GOOP", "GORE", "GORY", "GOSH", "GOTH", "GOUT", "GOWN", "GRAB", "GRAD", "GRAM", "GRAY", "GREW", "GREY",
  "GRID", "GRIM", "GRIN", "GRIP", "GRIT", "GROG", "GROW", "GRUB", "GULF", "GULL", "GULP", "GUMS", "GUNK",
  "GUNS", "GURU", "GUSH", "GUST", "GUTS", "GUYS", "GYMS", "HACK", "HAIL", "HAIR", "HAKE", "HALE", "HALF",
  "HALL", "HALO", "HALT", "HAMS", "HAND", "HANG", "HANK", "HARD", "HARE", "HARK", "HARM", "HARP", "HART",
  "HASH", "HASP", "HATE", "HATS", "HAUL", "HAVE", "HAWK", "HAZE", "HAZY", "HEAD", "HEAL", "HEAP", "HEAR",
  "HEAT", "HEED", "HEEL", "HEFT", "HEIR", "HELD", "HELL", "HELM", "HELP", "HEMP", "HEMS", "HENS", "HERB",
  "HERD", "HERE", "HERO", "HERS", "HEWN", "HICK", "HIDE", "HIGH", "HIKE", "HILL", "HILT", "HIND", "HINT",
  "HIPS", "HIRE", "HISS", "HITS", "HIVE", "HOAX", "HOBO", "HOCK", "HOED", "HOES", "HOGS", "HOLD", "HOLE",
  "HOLY", "HOME", "HONE", "HONK", "HOOD", "HOOF", "HOOK", "HOOP", "HOOT", "HOPE", "HOPS", "HORN", "HOSE",
  "HOST", "HOUR", "HOWL", "HUBS", "HUED", "HUES", "HUFF", "HUGE", "HUGS", "HULA", "HULK", "HULL", "HUMP",
  "HUMS", "HUNG", "HUNK", "HUNT", "HURL", "HURT", "HUSH", "HUSK", "HUTS", "HYMN", "HYPE", "ICED", "ICES",
  "ICKY", "ICON", "IDEA", "IDLE", "IDOL", "IFFY", "INCH", "INFO", "INKS", "INKY", "INNS", "INTO", "IONS",
  "IRIS", "IRKS", "IRON", "ISLE", "ITCH", "ITEM", "JABS", "JACK", "JADE", "JAIL", "JAMS", "JARS", "JAWS",
  "JAYS", "JAZZ", "JEAN", "JEEP", "JEER", "JELL", "JERK", "JEST", "JETS", "JIBE", "JIGS", "JILT", "JINX",
  "JIVE", "JOBS", "JOCK", "JOGS", "JOIN", "JOKE", "JOLT", "JOTS", "JOWL", "JOYS", "JUDO", "JUGS", "JUMP",
  "JUNE", "JUNK", "JURY", "JUST", "JUTS", "KALE", "KEEL", "KEEN", "KEEP", "KEGS", "KELP", "KEPT", "KEYS",
  "KICK", "KIDS", "KILL", "KILN", "KILT", "KIND", "KING", "KINK", "KISS", "KITE", "KITS", "KIWI", "KNEE",
  "KNEW", "KNIT", "KNOB", "KNOT", "KNOW", "LABS", "LACE", "LACK", "LACY", "LADS", "LADY", "LAGS", "LAID",
  "LAIR", "LAKE", "LAMB", "LAME", "LAMP", "LAND", "LANE", "LANK", "LAPS", "LARD", "LARK", "LASH", "LASS",
  "LAST", "LATE", "LATH", "LAUD", "LAVA", "LAWN", "LAWS", "LAYS", "LAZE", "LAZY", "LEAD", "LEAF", "LEAK",
  "LEAN", "LEAP", "LEFT", "LEGS", "LEND", "LENS", "LENT", "LESS", "LEST", "LETS", "LEVY", "LIAR", "LICE",
  "LICK", "LIDS", "LIED", "LIEN", "LIES", "LIEU", "LIFE", "LIFT", "LIKE", "LILT", "LILY", "LIMB", "LIME",
  "LIMP", "LINE", "LINK", "LINT", "LION", "LIPS", "LISP", "LIST", "LIVE", "LOAD", "LOAF", "LOAM", "LOAN",
  "LOBE", "LOBS", "LOCK", "LODE", "LOFT", "LOGO", "LOGS", "LOIN", "LONE", "LONG", "LOOK", "LOOM", "LOON",
  "LOOP", "LOOT", "LOPE", "LORD", "LORE", "LOSE", "LOSS", "LOST", "LOTS", "LOUD", "LOVE", "LOWS", "LUCK",
  "LULL", "LUMP", "LUNG", "LURE", "LURK", "LUSH", "LUTE", "LYNX", "LYRE", "MACE", "MADE", "MAID", "MAIL",
  "MAIM", "MAIN", "MAKE", "MALE", "MALL", "MALT", "MAMA", "MANE", "MANY", "MAPS", "MARE", "MARK", "MARS",
  "MART", "MASH", "MASK", "MASS", "MAST", "MATE", "MATH", "MATS", "MAUL", "MAZE", "MEAD", "MEAL", "MEAN",
  "MEAT", "MEEK", "MEET", "MELD", "MELT", "MEMO", "MEND", "MENU", "MEOW", "MERE", "MESH", "MESS", "MICE",
  "MILD", "MILE", "MILK", "MILL", "MIME", "MIND", "MINE", "MINI", "MINK", "MINT", "MIRE", "MISS", "MIST",
  "MITE", "MITT", "MOAN", "MOAT", "MOBS", "MOCK", "MODE", "MOLD", "MOLE", "MOLT", "MOMS", "MONK", "MOOD",
  "MOON", "MOOR", "MOOT", "MOPE", "MOPS", "MORE", "MORN", "MOSS", "MOST", "MOTH", "MOVE", "MOWS", "MUCH",
  "MUCK", "MUFF", "MUGS", "MULE", "MULL", "MUSE", "MUSH", "MUSK", "MUST", "MUTE", "MUTT", "MYTH", "NABS",
  "NAGS", "NAIL", "NAME", "NANA", "NAPE", "NAPS", "NAVY", "NEAR", "NEAT", "NECK", "NEED", "NEON", "NEST",
  "NETS", "NEWS", "NEWT", "NEXT", "NIBS", "NICE", "NICK", "NINE", "NIPS", "NODE", "NODS", "NONE", "NOOK",
  "NOON", "NOPE", "NORM", "NOSE", "NOSY", "NOTE", "NOUN", "NOVA", "NUDE", "NULL", "NUMB", "NUNS", "NUTS",
  "OAFS", "OAKS", "OARS", "OATH", "OATS", "OBEY", "ODDS", "ODES", "ODOR", "OILS", "OILY", "OINK", "OKAY",
  "OMEN", "OMIT", "ONCE", "ONES", "ONLY", "ONTO", "OOZE", "OPAL", "OPEN", "OPTS", "ORAL", "ORBS", "ORCA",
  "ORES", "OUCH", "OURS", "OUST", "OUTS", "OVAL", "OVEN", "OVER", "OWED", "OWES", "OWLS", "OWNS", "PACE",
  "PACK", "PACT", "PADS", "PAGE", "PAID", "PAIL", "PAIN", "PAIR", "PALE", "PALM", "PALS", "PANE", "PANG",
  "PANS", "PANT", "PAPA", "PARK", "PART", "PASS", "PAST", "PATE", "PATH", "PATS", "PAVE", "PAWN", "PAWS",
  "PAYS", "PEAK", "PEAL", "PEAR", "PEAS", "PEAT", "PECK", "PEEK", "PEEL", "PEEP", "PEER", "PEGS", "PELT",
  "PENS", "PENT", "PEON", "PERK", "PERM", "PERT", "PEST", "PETS", "PEWS", "PICK", "PIED", "PIER", "PIES",
  "PIGS", "PIKE", "PILE", "PILL", "PINE", "PING", "PINK", "PINS", "PINT", "PIPE", "PIPS", "PITA", "PITH",
  "PITS", "PITY", "PLAN", "PLAY", "PLEA", "PLED", "PLOD", "PLOP", "PLOT", "PLOW", "PLOY", "PLUG", "PLUM",
  "PLUS", "POCK", "PODS", "POEM", "POET", "POKE", "POKY", "POLE", "POLL", "POLO", "POMP", "POND", "PONY",
  "POOF", "POOL", "POOP", "POOR", "POPE", "POPS", "PORE", "PORK", "PORT", "POSE", "POSH", "POST", "POSY",
  "POTS", "POUR", "POUT", "PRAY", "PREP", "PREY", "PRIM", "PROD", "PROM", "PROP", "PROW", "PUBS", "PUCK",
  "PUFF", "PUGS", "PULL", "PULP", "PUMA", "PUMP", "PUNK", "PUNS", "PUNT", "PUNY", "PUPA", "PUPS", "PURE",
  "PURL", "PURR", "PUSH", "PUSS", "PUTS", "PUTT", "QUIT", "QUIZ", "RACE", "RACK", "RAFT", "RAGE", "RAGS",
  "RAID", "RAIL", "RAIN", "RAKE", "RAMP", "RAMS", "RANG", "RANK", "RANT", "RAPS", "RAPT", "RARE", "RASH",
  "RASP", "RATE", "RATS", "RAVE", "RAYS", "RAZE", "READ", "REAL", "REAM", "REAP", "REAR", "REDO", "REED",
  "REEF", "REEK", "REEL", "REIN", "RELY", "REND", "RENT", "REST", "RIBS", "RICE", "RICH", "RIDE", "RIDS",
  "RIFE", "RIFF", "RIFT", "RIGS", "RILE", "RIME", "RIMS", "RIND", "RING", "RINK", "RIOT", "RIPE", "RIPS",
  "RISE", "RISK", "RITE", "ROAD", "ROAM", "ROAR", "ROBE", "ROBS", "ROCK", "RODE", "RODS", "ROIL", "ROLE",
  "ROLL", "ROMP", "ROOF", "ROOK", "ROOM", "ROOT", "ROPE", "ROSE", "ROSY", "ROTS", "ROUT", "ROVE", "ROWS",
  "RUBS", "RUBY", "RUDE", "RUED", "RUES", "RUFF", "RUGS", "RUIN", "RULE", "RUMP", "RUNG", "RUNS", "RUNT",
  "RUSE", "RUSH", "RUST", "RUTS", "SACK", "SAFE", "SAGA", "SAGE", "SAID", "SAIL", "SAKE", "SALE", "SALT",
  "SAME", "SAND", "SANE", "SANG", "SANK", "SAPS", "SASH", "SASS", "SATE", "SAVE", "SAWS", "SAYS", "SCAB",
  "SCAM", "SCAN", "SCAR", "SCAT", "SEAL", "SEAM", "SEAR", "SEAS", "SEAT", "SECT", "SEED", "SEEK", "SEEM",
  "SEEN", "SEEP", "SEER", "SEES", "SELF", "SELL", "SEND", "SENT", "SETS", "SEWN", "SEWS", "SHAD", "SHAG",
  "SHAM", "SHED", "SHIN", "SHIP", "SHOD", "SHOE", "SHOO", "SHOP", "SHOT", "SHOW", "SHUN", "SHUT", "SICK",
  "SIDE", "SIFT", "SIGH", "SIGN", "SILK", "SILL", "SILO", "SILT", "SINE", "SING", "SINK", "SINS", "SIPS",
  "SIRE", "SIRS", "SITE", "SITS", "SIZE", "SKEW", "SKID", "SKIM", "SKIN", "SKIP", "SKIS", "SKIT", "SLAB",
  "SLAG", "SLAM", "SLAP", "SLAT", "SLAW", "SLAY", "SLED", "SLEW", "SLID", "SLIM", "SLIP", "SLIT", "SLOB",
  "SLOE", "SLOG", "SLOP", "SLOT", "SLOW", "SLUE", "SLUG", "SLUM", "SLUR", "SMOG", "SMUG", "SNAG", "SNAP",
  "SNIP", "SNIT", "SNOB", "SNOT", "SNOW", "SNUB", "SNUG", "SOAK", "SOAP", "SOAR", "SOBS", "SOCK", "SODA",
  "SODS", "SOFA", "SOFT", "SOIL", "SOLD", "SOLE", "SOLO", "SOME", "SONG", "SONS", "SOON", "SOOT", "SOPS",
  "SORE", "SORT", "SOUL", "SOUP", "SOUR", "SOWN", "SOWS", "SPAN", "SPAR", "SPAS", "SPAT", "SPAY", "SPEC",
  "SPED", "SPIN", "SPIT", "SPOT", "SPRY", "SPUD", "SPUN", "SPUR", "STAB", "STAG", "STAR", "STAT", "STAY",
  "STEM", "STEP", "STEW", "STIR", "STOP", "STOW", "STUB", "STUD", "STUN", "SUBS", "SUCH", "SUDS", "SUED",
  "SUES", "SUIT", "SULK", "SUMO", "SUMP", "SUMS", "SUNG", "SUNK", "SUNS", "SURE", "SURF", "SWAB", "SWAG",
  "SWAM", "SWAN", "SWAP", "SWAT", "SWAY", "SWIG", "SWIM", "SWOB", "SWOP", "SWUM", "TABS", "TACK", "TACO",
  "TACT", "TAGS", "TAIL", "TAKE", "TALE", "TALK", "TALL", "TAME", "TAMP", "TANG", "TANK", "TANS", "TAPE",
  "TAPS", "TARE", "TARN", "TARP", "TART", "TASK", "TAUT", "TAXI", "TEAK", "TEAL", "TEAM", "TEAR", "TEAS",
  "TEAT", "TECH", "TEED", "TEEM", "TEEN", "TEES", "TELL", "TEMP", "TEND", "TENS", "TENT", "TERM", "TERN",
  "TEST", "TEXT", "THAN", "THAT", "THAW", "THEE", "THEM", "THEN", "THEY", "THIN", "THIS", "THUD", "THUG",
  "THUS", "TICK", "TIDE", "TIDY", "TIED", "TIER", "TIES", "TILE", "TILL", "TILT", "TIME", "TINE", "TING",
  "TINS", "TINT", "TINY", "TIPS", "TIRE", "TOAD", "TOED", "TOES", "TOFU", "TOGA", "TOIL", "TOLD", "TOLL",
  "TOMB", "TOME", "TONE", "TONG", "TONS", "TOOK", "TOOL", "TOOT", "TOPS", "TORE", "TORN", "TORT", "TOSS",
  "TOTE", "TOTS", "TOUR", "TOUT", "TOWN", "TOWS", "TOYS", "TRAM", "TRAP", "TRAY", "TREE", "TREK", "TRIM",
  "TRIO", "TRIP", "TROD", "TROT", "TRUE", "TUBA", "TUBE", "TUBS", "TUCK", "TUFT", "TUGS", "TUNA", "TUNE",
  "TURF", "TURN", "TUSK", "TUTU", "TWIG", "TWIN", "TWIT", "TYKE", "TYPE", "TYPO", "UGLY", "UNDO", "UNIT",
  "UNTO", "UPON", "URGE", "URNS", "USED", "USER", "USES", "VAIN", "VALE", "VANE", "VANS", "VARY", "VASE",
  "VAST", "VATS", "VEAL", "VEER", "VEIL", "VEIN", "VEND", "VENT", "VERB", "VERY", "VEST", "VETO", "VETS",
  "VIAL", "VICE", "VIED", "VIES", "VIEW", "VILE", "VINE", "VISA", "VISE", "VOID", "VOLT", "VOTE", "VOWS",
  "WADE", "WADS", "WAFT", "WAGE", "WAGS", "WAIF", "WAIL", "WAIT", "WAKE", "WALK", "WALL", "WAND", "WANE",
  "WANT", "WARD", "WARE", "WARM", "WARN", "WARP", "WARS", "WART", "WARY", "WASH", "WASP", "WAVE", "WAVY",
  "WAXY", "WAYS", "WEAK", "WEAN", "WEAR", "WEBS", "WEDS", "WEED", "WEEK", "WEEP", "WELD", "WELL", "WELT",
  "WENT", "WEPT", "WERE", "WEST", "WETS", "WHAM", "WHAT", "WHEE", "WHEN", "WHET", "WHEY", "WHIM", "WHIP",
  "WHIR", "WHIT", "WHIZ", "WHOA", "WHOM", "WICK", "WIDE", "WIFE", "WIGS", "WILD", "WILE", "WILL", "WILT",
  "WILY", "WIMP", "WIND", "WINE", "WING", "WINK", "WINS", "WIPE", "WIRE", "WIRY", "WISE", "WISH", "WISP",
  "WITH", "WITS", "WOES", "WOKE", "WOLF", "WOMB", "WOOD", "WOOF", "WOOL", "WORD", "WORE", "WORK", "WORM",
  "WORN", "WOVE", "WRAP", "WREN", "WRIT", "YACK", "YAMS", "YANK", "YARD", "YARN", "YAWN", "YAWP", "YAWS",
  "YEAH", "YEAR", "YELL", "YELP", "YETI", "YIPE", "YOGA", "YOKE", "YOLK", "YOUR", "YOWL", "YUCK", "YULE",
  "ZANY", "ZAPS", "ZEAL", "ZERO", "ZEST", "ZINC", "ZING", "ZIPS", "ZONE", "ZOO", "ZOOM", "ZOOS"
].map(w => w.toUpperCase()));

// 16 Hand-Crafted, Kid-Tested Honeycomb Puzzles!
// Every puzzle has 20-50+ kid-friendly Emoji Words (starting at 3 letters!)
const PUZZLES = [
  {
    id: "sunny-meadow",
    title: "Sunny Meadow 🌻",
    center: "A",
    outer: ["C", "T", "R", "S", "B", "E"],
    themeEmoji: "🌻"
  },
  {
    id: "honey-tree",
    title: "Honey Tree 🐝",
    center: "E",
    outer: ["B", "T", "R", "S", "D", "N"],
    themeEmoji: "🐝"
  },
  {
    id: "beach-day",
    title: "Beach Day 🏖️",
    center: "A",
    outer: ["S", "N", "D", "L", "P", "T"],
    themeEmoji: "🏖️"
  },
  {
    id: "cozy-home",
    title: "Cozy Home 🏠",
    center: "O",
    outer: ["B", "T", "R", "K", "M", "D"],
    themeEmoji: "🏠"
  },
  {
    id: "puppy-pals",
    title: "Puppy Pals 🐶",
    center: "U",
    outer: ["P", "B", "G", "N", "S", "T"],
    themeEmoji: "🐶"
  },
  {
    id: "sweet-bakery",
    title: "Sweet Bakery 🎂",
    center: "A",
    outer: ["C", "K", "E", "B", "L", "M"],
    themeEmoji: "🎂"
  },
  {
    id: "starlight",
    title: "Starlight Sky ⭐",
    center: "I",
    outer: ["S", "T", "N", "G", "R", "P"],
    themeEmoji: "⭐"
  },
  {
    id: "rainy-pond",
    title: "Rainy Pond 🐸",
    center: "O",
    outer: ["F", "R", "G", "D", "P", "N"],
    themeEmoji: "🐸"
  },
  {
    id: "garden-seeds",
    title: "Garden Seeds 🌱",
    center: "E",
    outer: ["S", "D", "P", "L", "T", "W"],
    themeEmoji: "🌱"
  },
  {
    id: "farm-friends",
    title: "Farm Friends 🐷",
    center: "I",
    outer: ["P", "G", "K", "C", "H", "S"],
    themeEmoji: "🐷"
  },
  {
    id: "choo-choo",
    title: "Choo-Choo Train 🚂",
    center: "A",
    outer: ["T", "R", "I", "N", "C", "P"],
    themeEmoji: "🚂"
  },
  {
    id: "magic-wand",
    title: "Magic Crown 👑",
    center: "O",
    outer: ["C", "R", "W", "N", "D", "S"],
    themeEmoji: "👑"
  }
];
